Repository kubewarden/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#178 Release kubewarden-controller, kubewarden-defaults `1.3.0`
  charts/kubewarden-controller/Chart.yaml
  charts/kubewarden-controller/app-readme.md
  charts/kubewarden-controller/chart-values.yaml
  charts/kubewarden-controller/templates/_helpers.tpl
  charts/kubewarden-controller/templates/cert-tls.yaml
  charts/kubewarden-controller/templates/configmap.yaml
  charts/kubewarden-controller/templates/deployment.yaml
  charts/kubewarden-controller/templates/opentelemetry-collector.yaml
  charts/kubewarden-controller/templates/pre-delete-hook.yaml
  charts/kubewarden-controller/templates/rbac.yaml
  charts/kubewarden-controller/templates/service.yaml
  charts/kubewarden-controller/templates/serviceaccount.yaml
  charts/kubewarden-controller/templates/webhooks.yaml
  charts/kubewarden-controller/values.yaml
  charts/kubewarden-defaults/Chart.yaml
  charts/kubewarden-defaults/app-readme.md
  charts/kubewarden-defaults/chart-values.yaml
  charts/kubewarden-defaults/templates/_helpers.tpl
  charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
  charts/kubewarden-defaults/templates/capabilities-policy.yaml
  charts/kubewarden-defaults/templates/host-namespace-policy.yaml
  charts/kubewarden-defaults/templates/host-path-policy.yaml
  charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
  charts/kubewarden-defaults/templates/policy-server-rbac.yaml
  charts/kubewarden-defaults/templates/policyserver-default.yaml
  charts/kubewarden-defaults/templates/user-group-policy.yaml
  charts/kubewarden-defaults/values.yaml
Labels: kind/chore

#183 fix: updates kubewarden-defaults when we have a new CRD version.
  updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
  updatecli/updatecli.d/patch-kubewarden-controller.yaml
  updatecli/updatecli.d/patch-kubewarden-defaults.yaml
Labels: kind/bug, area/ci

#187 SecurityContext configuration
  charts/kubewarden-controller/chart-values.yaml
  charts/kubewarden-controller/templates/deployment.yaml
  charts/kubewarden-controller/templates/pre-delete-hook.yaml
  charts/kubewarden-controller/values.yaml
Labels: kind/enhancement

#186 Update chart releaser action used to v1.5.0
  .github/workflows/helm-chart-release.yml
Labels: area/ci, kind/chore

#192 Policy Server security configuration.
  charts/kubewarden-defaults/chart-values.yaml
  charts/kubewarden-defaults/templates/policyserver-default.yaml
  charts/kubewarden-defaults/values.yaml
Labels: kind/enhancement, area/charts
