Repository kubewarden/helm-charts, pull requests merged in 2023-02, with the labels that each got.

#193 chore: update recommended policies to latest versions.
  charts/kubewarden-defaults/Chart.yaml
  charts/kubewarden-defaults/chart-values.yaml
  charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
  charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
  charts/kubewarden-defaults/templates/user-group-policy.yaml
  charts/kubewarden-defaults/values.yaml
Labels: kind/chore

#195 fix: handle new monitoring namespace
  charts/kubewarden-defaults/chart-values.yaml
  charts/kubewarden-defaults/values.yaml
Labels: kind/bug, kind/enhancement

#196 Downgrade updatecli.
  .github/workflows/update-charts.yml
Labels: kind/bug, area/ci

#198 Downgrade updatecli to v2.19.0
  .github/workflows/update-charts.yml
Labels: kind/bug, area/ci
