Repository kubewarden/helm-charts, pull requests merged in 2024-03, with the labels that each got.

#386 fix(ci): fix broken updatecli yaml files.
  updatecli/updatecli.d/major-kubewarden-update.yaml
  updatecli/updatecli.d/prerelease-kubewarden-update.yaml
Labels: kind/bug, area/ci

#391 raise controller memory limits
  charts/kubewarden-controller/values.yaml
Labels: kind/bug

#397 chore: kubewarden-crds version bump.
  charts/kubewarden-controller/Chart.yaml
  charts/kubewarden-crds/Chart.yaml
  charts/kubewarden-defaults/Chart.yaml
Labels: kind/chore, area/charts

#407 Add job to update policies and kubectl image
  .github/workflows/update-dependencies.yaml
  charts/kubewarden-controller/values.yaml
  charts/kubewarden-defaults/templates/allow-privileged-escalation-policy.yaml
  charts/kubewarden-defaults/templates/capabilities-policy.yaml
  charts/kubewarden-defaults/templates/host-namespace-policy.yaml
  charts/kubewarden-defaults/templates/host-path-policy.yaml
  charts/kubewarden-defaults/templates/pod-privileged-policy.yaml
  charts/kubewarden-defaults/templates/user-group-policy.yaml
  charts/kubewarden-defaults/values.yaml
  renovate.json
  updatecli/DEVELOP.md
  updatecli/updatecli.d/major-kubewarden-update.yaml
  updatecli/updatecli.d/patch-kubewarden-controller-with-crds-update.yaml
  updatecli/updatecli.d/patch-kubewarden-controller.yaml
  updatecli/updatecli.d/patch-kubewarden-defaults.yaml
  updatecli/updatecli.d/prerelease-kubewarden-update-with-crd-update.yaml
  updatecli/updatecli.d/prerelease-kubewarden-update.yaml
  updatecli/updatecli.d/update-deps.yaml
Labels: kind/enhancement, area/ci, kind/breaking-change, area/automation
